#!/bin/sh

# Linux Setup

# Editing....

sudo apt-get update
sudo apt-get upgrade

sudo apt-get install git-extras
sudo apt-get install git-flow
sudo apt-get install httpie
sudo apt-get install zsh

#  ---------------   zsh ohmysh  ----------------------		

sudo apt-get install git-core
wget https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | zsh
chsh -s `which zsh`

#  ---------------   z  ----------------------		

curl https://raw.githubusercontent.com/rupa/z/master/z.sh -o z.sh 
# put something like this in your .bashrc/.zshrc:
#         . /path/to/z.sh

#  ---------------   helm  ----------------------		            
curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 && chmod 700 get_helm.sh
./get_helm.sh

#  ---------------   kubectl  ----------------------

sudo apt-get update && sudo apt-get install -y apt-transport-https
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
sudo apt-get update
sudo apt-get install -y kubectl

#  ---------------   kubectx && kubens  ----------------------

sudo git clone https://github.com/ahmetb/kubectx /opt/kubectx
sudo ln -s /opt/kubectx/kubectx /usr/local/bin/kubectx
sudo ln -s /opt/kubectx/kubens /usr/local/bin/kubens

#  ---------------   kube-ps1  ----------------------
curl https://github.com/jonmosco/kube-ps1/archive/v0.7.0.tar.gz

#[BASH]
source /path/to/kube-ps1.sh
PS1='[\u@\h \W $(kube_ps1)]\$ '

#  ---------------  kubetail sterm (using zsh.ohmysh) ----------------------

cd ~/.oh-my-zsh/custom/plugins/
git clone https://github.com/johanhaleby/kubetail.git kubetail
#...




#NO COMPLETE (tienen duda)kube-ps1 , kubetail

